server.port: 8081

spring:
  application.name: crawler
  config:
    import:
      - "optional:file:server/crawler/.env[.properties]"
      - "classpath:config/ai.yml"

streams:
  ai-analysis-crawling: ${STREAMS_AI_ANALYSIS_CRAWLING_KEY}
  ai-analysis-review: ${STREAMS_AI_ANALYSIS_REVIEW_KEY}
  ai-analysis-dlq: ${STREAMS_AI_ANALYSIS_DLQ_KEY}
  group: ${STREAMS_GROUP}

logging:
  level:
    org.springframework.ai.retry: ERROR
