global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kustaurant-api-host'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'mysqld_exporter'
    static_configs:
      - targets: [ 'mysqld-exporter:9104' ]

  - job_name: 'crawler-host'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['${CRAWLER_HOST}']