server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: "http://${LOKI_HOST}:3100/loki/api/v1/push"

scrape_configs:
  - job_name: crawler
    static_configs:
      - targets: [ localhost ]
        labels:
          job: crawler
          app: crawler
          env: prod
          __path__: /var/log/crawler/*.log

    pipeline_stages:
      - json:
          expressions:
            ts: '["@timestamp"]'
            level: level
            logger: logger_name
            msg: message
            thread: thread_name
      - timestamp:
          source: ts
          format: RFC3339Nano
      - labels:
          level:
